version: '3.1'
services:
  kafka:
    image: bitnami/kafka:3.4.1
    ports:
    - "9092:9092"
    container_name: camunda_kafka
    environment:

      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller, broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093

      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092, CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT